%% LOAD MODEL
%% This functions loads the shuttle cock configuration sattelite
%  from .obj files stored in the example folder
function bodies = load_model()
    import vleo_aerodynamics_core.*
    % Get absolute path of test folder
    %[test_folder,~,~] = fileparts(mfilename("fullpath"));
    [test_folder,~,~] = fileparts(matlab.desktop.editor.getActiveFilename);
    disp(test_folder)
    object_files = string(fullfile(test_folder, 'obj', ...
                                 {'MainBody.obj', ...
                                 'WingBottom.obj', ...
                                 'WingTop.obj',...
                                 'WingRight.obj',...
                                 'WingLeft.obj'
                                 }));

    surface_temperatures__K = num2cell(300*(0:4));
    surface_energy_accommodation_coefficients = num2cell(0.01*ones(1,5));

    rotation_hinge_points_CAD = [0,0,0,0.05,-0.05;...
                                0,-0.05,0.05,0,0;...
                                0,0,0,0,0];

    rotation_directions_CAD = [1,-1,1,0,0;...
                                0,0,0,-1,1;...
                                0,0,0,0,0];

    DCM_B_from_CAD = [0, 0, 1;...
                        0, 1, 0; ...
                        -1, 0, 0];
    %DCM_B_from_CAD = eye(3);
    CoM_CAD = [0; 0; 0.1];

    bodies = importMultipleBodies(object_files, ...
        rotation_hinge_points_CAD, ...
        rotation_directions_CAD, ...
        surface_temperatures__K, ...
        surface_energy_accommodation_coefficients, ...
        DCM_B_from_CAD, ...
        CoM_CAD);
end